# These are the asset types that will be skipped by the Lister.
#
# Full list of asset types is in asset-types.properties.
#
# Development of new asset types: See comment at top of asset-types.properties.
#
# The regex  is a full-string match on the local asset name, for example the Topic or Instance name.
#
# For example:
#
# 1. The lines
#          appengine.googleapis.com/Version:
#            regex: "foo.*"
#            listThese: false
#
#     are used for a blacklist: GAE Versions with names like foo and foobar will be skipped in listing.
#     However, quuxfoo will NOT be skipped as there is no full-string match;
#        for a partial-string match you could use ".*foo.*".
#
# 2. The same thing but with
#            listThese: true
#    is used for a whitelist: that only names foo and foobar and other full-string-matching names will be listed.
#
# 3. To list nothing in a given service
#          appengine.googleapis.com/Version:
#            regex: "UNSUPPORTED"
#            listThese: true
#
# 4. To list everything in a given service, leave the key's value blank, as in the samples below.
#
compute.googleapis.com/Firewall:
  regex: ^default-.*
  listThese: false
compute.googleapis.com/Subnetwork:
  regex: ^default.*
  listThese: false
appengine.googleapis.com/Version:
appengine.googleapis.com/Service:
cloudfunctions.googleapis.com/CloudFunction:
compute.googleapis.com/Address:
compute.googleapis.com/Disk:
compute.googleapis.com/BackendBucket:
compute.googleapis.com/BackendService:
compute.googleapis.com/ForwardingRule:
compute.googleapis.com/GlobalForwardingRule:
compute.googleapis.com/HealthCheck:
compute.googleapis.com/Instance:
compute.googleapis.com/TargetHttpProxy:
compute.googleapis.com/TargetHttpsProxy:
compute.googleapis.com/UrlMap:
container.googleapis.com/Cluster:
pubsub.googleapis.com/Subscription:
pubsub.googleapis.com/Topic:
storage.googleapis.com/Bucket:
logging.googleapis.com/LogMetric:
run.googleapis.com/Service:
sqladmin.googleapis.com/Instance:
